- name: Deploy Hospital App
  hosts: app_server
  become: yes

  vars:
    image_name: suprit43/hp_webapp
    tag: "{{ tag }}"
    container_name: hospital-app
    app_port: 80

  tasks:

    - name: Remove old container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ tag }}"
        state: started
        pull: yes
        restart_policy: always
        ports:
          - "{{ app_port }}:8080"